// ── DIE ORTSNAMEN AUF ENGLISCH ──────────────────────────────────────────────
// v1.0.15 (Besitzer: "Mach alle Ortsnamen auf Englisch"): Die 529 Stationen
// der zwoelf Kapitel trugen bisher NUR ihren deutschen Namen - im englischen
// Spiel stand also mitten in einem englischen Satz "Wo die Sense ruht".
//
// Warum eine KARTE und keine zweite Namensliste: die Namen stehen fest in
// campaign12.gen.js (Feld "place"), einmal gebaut aus content/placeNames.js.
// Eine zweite Liste muesste Zeile fuer Zeile mit dem Generat in Deckung
// bleiben - ein Fehler, der niemandem auffaellt, bis eine Station den Namen
// einer anderen traegt. Die Karte schlaegt stattdessen den deutschen Namen
// nach; was sie nicht kennt, bleibt stehen, statt zu verschwinden.
//
// Uebersetzt ist nach KLANG, nicht Wort fuer Wort: ein Ortsname muss auf
// einer Karte stehen koennen. "Zehntwacht" wird "Tithe Watch", nicht
// "Tenth Guard"; "Windfluechter" (die vom Wind gebeugten Baeume) werden
// "The Windshaped". Eigennamen der Chronik - Osric, Asra, Vesna - bleiben.
//
// Ein Test in test_maps.mjs haelt drei Dinge fest: jede Station hat einen
// englischen Namen, keiner doppelt sich, und keiner ist versehentlich
// deutsch geblieben.

export const PLACE_EN = {
  "Abbruchkante": "Breakaway Edge",
  "Adlerkanzel": "Eagle's Pulpit",
  "Adlermesse": "Eagle Mass",
  "Adlerstein": "Eaglestone",
  "Ahornbrück": "Maple Span",
  "Almabtrieb": "The Cattle Descent",
  "Almglocken": "Pasture Bells",
  "Almrast": "Pasture Rest",
  "Alte Sternwarte": "The Old Observatory",
  "Alte Wacht": "Old Watch",
  "Alter Markt": "The Old Market",
  "Amselthron": "Blackbird Throne",
  "Ankerfriedhof": "Anchor Graveyard",
  "Aschengarbe": "Ash Sheaf",
  "Aschepfand": "Ash Pledge",
  "Aschesegel": "Ash Sail",
  "Asras Brunnen": "Asra's Well",
  "Ausgetrocknet": "Run Dry",
  "Aussichtsnadel": "The Lookout Needle",
  "Bannergrund": "Banner Ground",
  "Bannerhöhe": "Banner Height",
  "Barfußspur": "Barefoot Trail",
  "Bei den Pferdehirten": "Among the Horse Herders",
  "Bei den Schnittern": "Among the Reapers",
  "Bei den Steinmetzen": "Among the Stonemasons",
  "Bei den Strandläufern": "Among the Shore Runners",
  "Bei den Wasserträgern": "Among the Water Carriers",
  "Bergahornhof": "Sycamore Farm",
  "Bernsteinaltar": "Amber Altar",
  "Bittersalz": "Bitter Salt",
  "Blasebalg": "The Bellows",
  "Blaue Grotte": "Blue Grotto",
  "Blaue Wand": "The Blue Wall",
  "Bleicher Horizont": "Pale Horizon",
  "Bleichgart": "Bleachgarth",
  "Blitzfeste des Grossmeisters": "The Grandmaster's Lightning Hold",
  "Blutzoll": "Blood Toll",
  "Blätterkahn": "Leafboat",
  "Bohlenweg": "The Plank Road",
  "Brackwasserbrücke": "Brackwater Bridge",
  "Brackwasserklause": "Brackwater Hermitage",
  "Brandblatt": "Scorchleaf",
  "Brandschneise": "Firebreak",
  "Bussardstand": "Buzzard Stand",
  "Böenritt": "Squall Ride",
  "Das Ausgeblutete Tor": "The Bled-Out Gate",
  "Das Berstende Gatter": "The Bursting Grate",
  "Das Berstende Tor": "The Bursting Gate",
  "Das Erfrorene Tor": "The Frozen Gate",
  "Das Ertrunkene Tor": "The Drowned Gate",
  "Das Ferne Tor": "The Far Gate",
  "Das Flüsternde Tor": "The Whispering Gate",
  "Das Glühende Tor": "The Glowing Gate",
  "Das Rostige Tor": "The Rusted Gate",
  "Das Verlorene Schloss": "The Lost Lock",
  "Das Verriegelte Tor": "The Bolted Gate",
  "Das Versandete Tor": "The Sanded Gate",
  "Dattelhain": "Date Grove",
  "Der Erstarrte Hain": "The Stiffened Grove",
  "Der Fennekpfad": "The Fennec Path",
  "Der Ferne Riegel": "The Far Bolt",
  "Der Fürst im Halbschatten": "The Lord in Half-Shadow",
  "Der Galgenpfad": "The Gallows Path",
  "Der Gamssteig": "The Chamois Track",
  "Der Geduckte Forst": "The Crouching Forest",
  "Der Hüter ohne Tür": "The Keeper Without a Door",
  "Der Kahle Rücken": "The Bare Ridge",
  "Der Kanonier am Wasser": "The Gunner by the Water",
  "Der Kondorpfad": "The Condor Path",
  "Der Krumme Hain": "The Crooked Grove",
  "Der Letzte Schatten": "The Last Shadow",
  "Der Leuchtturm": "The Lighthouse",
  "Der Meister der Lanze": "The Master of the Lance",
  "Der Möwenstrich": "The Gull Line",
  "Der Rehpfad": "The Deer Path",
  "Der Rostige Riegel": "The Rusted Bolt",
  "Der Schiefe Zaun": "The Leaning Fence",
  "Der Schweigende Halm": "The Silent Stalk",
  "Der Singende Fels": "The Singing Rock",
  "Der Steile Anger": "The Steep Green",
  "Der Steinerne Pflug": "The Stone Plough",
  "Der Stumme Hain": "The Mute Grove",
  "Der Versteinerte Hain": "The Petrified Grove",
  "Der Wildwechsel": "The Game Trail",
  "Der Wildwechsel II": "The Game Trail II",
  "Der Wispernde Halm": "The Whispering Stalk",
  "Der Zerzauste Wald": "The Tousled Wood",
  "Der Zugefrorene Riegel": "The Frozen Bolt",
  "Der erste Anstieg": "The First Climb",
  "Der geteilte Schwur": "The Divided Vow",
  "Der lange Acker": "The Long Field",
  "Der letzte Steg": "The Last Jetty",
  "Die Faust am Grund": "The Fist at the Bottom",
  "Die Kahle Kuppe": "The Bare Crown",
  "Die Magd am Kelch": "The Maid at the Chalice",
  "Die Schindelhütte": "The Shingle Hut",
  "Die Stille See": "The Still Sea",
  "Die Stumme Glocke": "The Mute Bell",
  "Die Windflüchter": "The Windshaped",
  "Die Wolfsspur": "The Wolf Trail",
  "Die Wolkenweide": "The Cloud Pasture",
  "Die Zwei Wetterfichten": "The Two Weather Spruces",
  "Die letzte Alm": "The Last Pasture",
  "Distelwind": "Thistlewind",
  "Dohlenflug": "Jackdaw Flight",
  "Donnerkar": "Thunder Cirque",
  "Dornendiadem": "Thorn Diadem",
  "Dornenfeste": "Thorn Hold",
  "Dornengesims": "Thorn Ledge",
  "Dornengürtel": "Thorn Girdle",
  "Dornenkelch": "Thorn Chalice",
  "Dreschhof": "Threshing Yard",
  "Drosselsang": "Thrushsong",
  "Dämmerlaube": "Dusk Arbour",
  "Dörrkammer": "The Drying Room",
  "Dünenaltar": "Dune Altar",
  "Dünenwerder": "Dune Holm",
  "Dürretor": "Drought Gate",
  "Ebbe und Niemand": "Low Tide and No One",
  "Echostille": "Echo Silence",
  "Eichelschatz": "Acorn Hoard",
  "Einsame Boje": "The Lone Buoy",
  "Einsiedlerloch": "Hermit's Hollow",
  "Eisbucht": "Ice Bay",
  "Eisburg": "Ice Keep",
  "Eisenblüte": "Ironbloom",
  "Eisenbollwerk": "Iron Bulwark",
  "Eiserne Untiefe": "The Iron Shallows",
  "Eiskahn": "Ice Barge",
  "Eisnadel": "Ice Needle",
  "Erntedank": "Harvest Thanks",
  "Erntewiege": "Harvest Cradle",
  "Erste Gischt": "First Spray",
  "Erster Grat": "First Ridge",
  "Erster Grat II": "First Ridge II",
  "Erster Riss": "First Rift",
  "Erstes Rot": "First Red",
  "Eulenwarte": "Owl Watch",
  "Fahles Land": "Pallid Country",
  "Fahnenwind": "Banner Wind",
  "Falbes Licht": "Dun Light",
  "Falkenkanzel": "Falcon's Pulpit",
  "Fallendes Laub": "Falling Leaves",
  "Fallenstellerlager": "Trapper's Camp",
  "Fata Morgana": "Fata Morgana",
  "Feldkapelle": "Field Chapel",
  "Felsenfenster": "The Rock Window",
  "Felsenhorst": "Crag Eyrie",
  "Firnhang": "Firn Slope",
  "Firnriss": "Firn Rift",
  "Firnscharte": "Firn Notch",
  "Flammenfurt": "Flame Ford",
  "Flaschenpost": "Message in a Bottle",
  "Flechtenteppich": "Lichen Carpet",
  "Flimmerhitze": "Shimmer Heat",
  "Flirrende Luft": "Quivering Air",
  "Freier Himmel": "Open Sky",
  "Fronburg": "Bondage Keep",
  "Frostbeulen": "Chilblains",
  "Frostglockenturm": "Frost Bell Tower",
  "Frostthron": "Frost Throne",
  "Fuchsfurt": "Fox Ford",
  "Fuhrmannsrast": "Carter's Rest",
  "Furt am Grauen Bach": "Ford at the Grey Brook",
  "Furtlose Enge": "The Fordless Narrows",
  "Fährmannsruf": "Ferryman's Call",
  "Fährtenfeld": "Trailfield",
  "Fürstenmahd": "The Prince's Mowing",
  "Galgenhöhe": "Gallows Height",
  "Gamswechsel": "Chamois Crossing",
  "Garbenwall": "Sheaf Rampart",
  "Gebeugte Kapelle": "The Bowed Chapel",
  "Gebleichte Rippen": "Bleached Ribs",
  "Gefrorene Träne": "The Frozen Tear",
  "Geierkanzel": "Vulture's Pulpit",
  "Geierschatten": "Vulture Shadow",
  "Geisterfeld": "Ghost Field",
  "Gekentertes Glück": "Capsized Fortune",
  "Geröllrutsche": "Scree Slide",
  "Geröllzunge": "Scree Tongue",
  "Gezeitenklinge": "Tide Blade",
  "Gilbfeuer": "Yellowfire",
  "Gipfelaltar": "Summit Altar",
  "Gipfelkron": "Summit Crown",
  "Gipfelruh": "Summit Rest",
  "Gischtthron": "Spray Throne",
  "Glasfeld": "Glass Field",
  "Gletschermilch": "Glacier Milk",
  "Glutkamm": "Ember Ridge",
  "Glutofen": "The Furnace",
  "Glutspiegel": "Ember Mirror",
  "Glutstoppel": "Ember Stubble",
  "Grabesgeröll": "Grave Scree",
  "Grasklause": "Grass Hermitage",
  "Grasklinge": "Grass Blade",
  "Grasmeer": "Sea of Grass",
  "Grathelm": "Ridge Helm",
  "Gratrast": "Ridge Rest",
  "Graudorn": "Greythorn",
  "Grauer Atem": "Grey Breath",
  "Grauschleier": "Grey Veil",
  "Grenzmark": "Border March",
  "Grenzstein": "Boundary Stone",
  "Grenzwall": "Border Rampart",
  "Grubenlampen": "Pit Lamps",
  "Halle der geballten Faust": "Hall of the Clenched Fist",
  "Halle der herrenlosen Fracht": "Hall of the Ownerless Cargo",
  "Halle der leeren Regale": "Hall of the Empty Shelves",
  "Halle der stillen Kälte": "Hall of the Silent Cold",
  "Halle der zwei Schwüre": "Hall of the Two Vows",
  "Halle des einen Gangs": "Hall of the Single Tilt",
  "Halle des letzten Tors": "Hall of the Last Gate",
  "Halle des vollen Kelchs": "Hall of the Full Chalice",
  "Halmbruch": "Stalkbreak",
  "Hammerschlag": "Hammerfall",
  "Hangdorf": "Slopeton",
  "Harzträne": "Resin Tear",
  "Heckenrondell": "Hedge Round",
  "Heiße Quelle": "Hot Spring",
  "Hexenmoor": "Witch Moor",
  "Hirtenkanzel": "Shepherd's Pulpit",
  "Hirtenruh": "Shepherd's Rest",
  "Hochleger": "High Steading",
  "Hochwacht": "High Watch",
  "Hoher Ausguck": "High Lookout",
  "Hoher Kamm": "High Crest",
  "Hohes Heiligtum": "High Sanctuary",
  "Hufdonner": "Hoofthunder",
  "Hufdonner II": "Hoofthunder II",
  "Hufeisenglück": "Horseshoe Luck",
  "Hufschlagring": "Hoofbeat Ring",
  "Hängebrück": "Hanging Span",
  "Hängender Weiler": "The Hanging Hamlet",
  "Hüttenrauch": "Hut Smoke",
  "Jagdrast": "Hunter's Rest",
  "Jurtenring": "Yurt Ring",
  "Jurtenring II": "Yurt Ring II",
  "Jägersitz": "Hunter's Seat",
  "Jägersteig": "Hunter's Track",
  "Kalkhöhle": "Limestone Cave",
  "Kalter Sog": "Cold Undertow",
  "Kamelspur": "Camel Trail",
  "Kammweg": "Crest Way",
  "Kanzel der Wunde": "Pulpit of the Wound",
  "Kanzel im Weizen": "Pulpit in the Wheat",
  "Kap der Fracht": "Cape of Cargo",
  "Kap der Stille": "Cape of Silence",
  "Kapelle im Korn": "Chapel in the Corn",
  "Karawanenglocke": "Caravan Bell",
  "Karawanserei": "Caravanserai",
  "Kastanienhall": "Chestnut Hall",
  "Kelchmesse": "Chalice Mass",
  "Kielwasser": "Wake Water",
  "Klammglocke": "Gorge Bell",
  "Klingenschlucht": "Blade Gorge",
  "Klingenwald": "Blade Wood",
  "Kluftfeste": "Cleft Hold",
  "Kluftmesse": "Cleft Mass",
  "Klufttreppe": "Cleft Stair",
  "Knirschsteg": "Creaking Walk",
  "Kondorkanzel": "Condor's Pulpit",
  "Kristallader": "Crystal Vein",
  "Kronenstadt": "Crown City",
  "Krumme Klippe": "Crooked Cliff",
  "Krähenfels": "Crow Rock",
  "Krähennest": "Crow's Nest",
  "Krähenschreck": "Crow Scare",
  "Kupferader": "Copper Vein",
  "Käserast": "Cheesemaker's Rest",
  "Köhlersitz": "Charcoaler's Seat",
  "Königsallee": "King's Avenue",
  "Königsdurst": "King's Thirst",
  "Königsdüne": "King's Dune",
  "Königsgrat": "King's Ridge",
  "Königsjoch": "King's Saddle",
  "Königsklippe": "King's Cliff",
  "Königslaub": "King's Foliage",
  "Königsschlucht": "King's Gorge",
  "Königsstroh": "King's Straw",
  "Königsweide": "King's Pasture",
  "Lakensenke": "Sheet Hollow",
  "Lastenrast": "Burden Rest",
  "Latschenfeld": "Dwarf Pine Field",
  "Laubpresse": "Leaf Press",
  "Lawinenhang": "Avalanche Slope",
  "Leere Scheune": "The Empty Barn",
  "Lerchenhorst": "Lark's Nest",
  "Letzte Schranke": "The Last Barrier",
  "Letzter Schluck": "The Last Sip",
  "Leuchtfeuermesse": "Beacon Mass",
  "Leuchtfeuerrest": "Beacon Remnant",
  "Lied der Weite": "Song of the Wide Land",
  "Lindenhain": "Linden Grove",
  "Lindenschatten": "Linden Shade",
  "Lindensitz": "Linden Seat",
  "Lärchentor": "Larch Gate",
  "Marchstein": "Marchstone",
  "Marderschlupf": "Marten's Burrow",
  "Marterpfad": "Torment Path",
  "Mastbruch": "Mastbreak",
  "Maultiersteige": "Mule Track",
  "Mautbalken": "The Toll Bar",
  "Meißelschlag": "Chiselstroke",
  "Messerschlucht": "Knife Gorge",
  "Milchsee": "Milk Lake",
  "Mittsommerbank": "Midsummer Bench",
  "Modergraben": "Mould Ditch",
  "Moderpforte": "Mould Gate",
  "Mohnwerder": "Poppy Holm",
  "Mondwarte": "Moon Watch",
  "Morschenburg": "Rotwood Keep",
  "Murmelfeld": "Marmot Field",
  "Murmelloch": "Marmot Hole",
  "Murmeltierstadt": "Marmot Town",
  "Muschelscherben": "Shell Shards",
  "Möwenkanzel": "Gull's Pulpit",
  "Mühlensteg": "Mill Walk",
  "Nachtwand": "Night Wall",
  "Namenlose Weite": "The Nameless Expanse",
  "Nebelbank": "Fog Bank",
  "Nebelmeerblick": "View of the Cloud Sea",
  "Nebelmoor": "Mist Moor",
  "Nebelweide": "Mist Pasture",
  "Nordlichtkanzel": "Aurora Pulpit",
  "Nordwacht": "North Watch",
  "Oasenmesse": "Oasis Mass",
  "Oberkante": "The Upper Edge",
  "Ockergrund": "Ochre Ground",
  "Ockerwanne": "Ochre Basin",
  "Osrics Speicher": "Osric's Granary",
  "Osrics letztes Tor": "Osric's Last Gate",
  "Palmschatten": "Palm Shade",
  "Perlmuttgrotte": "Mother-of-Pearl Grotto",
  "Piersplitter": "Pier Splinters",
  "Pilgerpfad": "Pilgrim's Path",
  "Pilzring": "Fairy Ring",
  "Planke über Schwarz": "Plank Over Black",
  "Plünderersitz": "Plunderer's Seat",
  "Quellen unterm Eis": "Springs Beneath the Ice",
  "Rabenacker": "Raven Field",
  "Rabenkanzel": "Raven's Pulpit",
  "Rabenstieg": "Raven Track",
  "Rast am Abgrund": "Rest at the Abyss",
  "Rast am Schlund": "Rest at the Maw",
  "Rast der Durstigen": "Rest of the Thirsty",
  "Rast der Erschöpften": "Rest of the Exhausted",
  "Rast der Gestrandeten": "Rest of the Stranded",
  "Rast der Reiter": "Rest of the Riders",
  "Rast der Verlorenen": "Rest of the Lost",
  "Ratshalle": "Council Hall",
  "Raureifgitter": "Hoarfrost Lattice",
  "Reisigschneise": "Brushwood Cut",
  "Reiteraltar": "Rider's Altar",
  "Reiteraltar II": "Rider's Altar II",
  "Riff der Rippen": "Reef of Ribs",
  "Robbenbank": "Seal Bank",
  "Rostlaube": "Rust Bower",
  "Rostregen": "Rust Rain",
  "Räubersitz": "Robber's Seat",
  "Salzfels": "Salt Rock",
  "Salzkruste": "Salt Crust",
  "Salzleck": "Salt Lick",
  "Salzlippen": "Salt Lips",
  "Sandhose": "Sand Devil",
  "Sandklause": "Sand Hermitage",
  "Sattelfeste": "Saddle Hold",
  "Schattenklippe": "Shadow Cliff",
  "Scherbengrat": "Shard Ridge",
  "Schieferwiege": "Slate Cradle",
  "Schilfmeer": "Sea of Reeds",
  "Schlangenloch": "Serpent Hole",
  "Schlüsselbund": "The Keyring",
  "Schlüsselzinne": "Key Pinnacle",
  "Schmiedegrund": "Forge Ground",
  "Schneegrenze": "Snowline",
  "Schneelinde": "Snow Linden",
  "Schutthalde": "Rubble Slope",
  "Schuttrinne": "Rubble Chute",
  "Schwalbennische": "Swallow's Niche",
  "Schwelnest": "Smoulder Nest",
  "Schwelrain": "Smoulder Bank",
  "Schwindelsteg": "Vertigo Walk",
  "Seegraswiege": "Seagrass Cradle",
  "Seilbrück": "Rope Span",
  "Seilpfad": "Rope Path",
  "Seilrolle": "The Pulley",
  "Seilwinde": "The Winch",
  "Sennenwacht": "Herdsman's Watch",
  "Sichelbucht": "Sickle Bay",
  "Sichelgrab": "Sickle Grave",
  "Sichelmark": "Sickle March",
  "Sieben Palmen": "Seven Palms",
  "Sieben Riegel": "Seven Bolts",
  "Siegerquell": "Victor's Spring",
  "Silbermühle": "Silver Mill",
  "Skarabäenfeld": "Scarab Field",
  "Sonnenhang": "Sun Slope",
  "Sonnenheiligtum": "Sun Sanctuary",
  "Sonnenspeer": "Sunspear",
  "Spiegelung": "The Mirage",
  "Spiegelzinne": "Mirror Pinnacle",
  "Splitterbrück": "Splinter Span",
  "Splitterkar": "Splinter Cirque",
  "Splitterknochen": "Splintered Bone",
  "Spreugericht": "Chaff Court",
  "Sprödes Bett": "The Brittle Bed",
  "Stachelnest": "Spine Nest",
  "Staubglocke": "Dust Bell",
  "Staubwalze": "Dust Roller",
  "Steinbockstand": "Ibex Stand",
  "Steinerne Stube": "The Stone Parlour",
  "Steinerner Schlaf": "Stone Sleep",
  "Steinernes Tor": "The Stone Gate",
  "Steinkreis": "Stone Circle",
  "Steinmandl": "Cairn Man",
  "Steinmesse": "Stone Mass",
  "Steinmetzsitz": "Stonemason's Seat",
  "Steinrose": "Stone Rose",
  "Steinrosen": "Stone Roses",
  "Steinschlag": "Rockfall",
  "Steppenkron": "Steppe Crown",
  "Steppenulme": "Steppe Elm",
  "Sternenlager": "Starlit Camp",
  "Sternenpfad": "Star Path",
  "Strandgutlese": "Flotsam Gleaning",
  "Stromschnellenfurt": "Rapids Ford",
  "Sturmauge": "Storm Eye",
  "Sturmfeste": "Storm Hold",
  "Sturmglas": "Storm Glass",
  "Sturmlaub": "Storm Foliage",
  "Stutenmilch": "Mare's Milk",
  "Talenge": "The Valley Narrows",
  "Talsperre": "The Barrage",
  "Tangwald": "Kelp Wood",
  "Taustelle": "Dewpoint",
  "Tidenglocke": "Tide Bell",
  "Tiefbrunnen": "Deep Well",
  "Tiefenblick": "Deep Sight",
  "Tintengrund": "Ink Ground",
  "Torfstich": "Peat Cut",
  "Totes Geäst": "Dead Boughs",
  "Treibholzfeld": "Driftwood Field",
  "Treibholzufer": "Driftwood Shore",
  "Treibnetz": "Drift Net",
  "Treibsandfalle": "Quicksand Trap",
  "Trockene Tränke": "The Dry Trough",
  "Trockentor": "Dry Gate",
  "Tropfstein": "Dripstone",
  "Tropfsteinorgel": "Dripstone Organ",
  "Turniermesse": "Tourney Mass",
  "Vereiste Klause": "The Iced Hermitage",
  "Vereister Altar": "The Iced Altar",
  "Verfallene Klause": "The Ruined Hermitage",
  "Vergessene Zisterne": "The Forgotten Cistern",
  "Vergessener Schrein": "The Forgotten Shrine",
  "Verhüllter Altar": "The Veiled Altar",
  "Verlassene Jurte": "The Abandoned Yurt",
  "Verlassene Kate": "The Abandoned Cottage",
  "Verlassene Ruinen": "The Abandoned Ruins",
  "Verlassener Kai": "The Abandoned Quay",
  "Verlassener Stollen": "The Abandoned Adit",
  "Versunkener Wachtturm": "The Sunken Watchtower",
  "Verwaiste Hütte": "The Orphaned Hut",
  "Vesnas Schatten": "Vesna's Shadow",
  "Viehtrift": "Cattle Drift",
  "Volle Scheuer": "The Full Granary",
  "Waage und Wort": "Scales and Word",
  "Wachtbaum": "Watch Tree",
  "Wachtfels": "Watch Rock",
  "Waldfeste": "Forest Hold",
  "Wanderdüne": "Wandering Dune",
  "Wandererrast": "Wanderer's Rest",
  "Wasserprobe": "The Water Trial",
  "Weidewende": "Pasture Turn",
  "Weites Rund": "The Wide Round",
  "Weites Rund II": "The Wide Round II",
  "Welkgart": "Witherarth",
  "Wellenwacht": "Wave Watch",
  "Wende des Lichts": "The Turning of the Light",
  "Wetterbaum": "Weather Tree",
  "Wetterhahnturm": "Weathercock Tower",
  "Wildheuplatz": "Wild Hay Ground",
  "Windfähre": "Wind Ferry",
  "Windgeschliffen": "Wind-Honed",
  "Windkamm": "Wind Crest",
  "Windzinne": "Wind Pinnacle",
  "Wipfelkanzel": "Treetop Pulpit",
  "Wo der Atem gefror": "Where the Breath Froze",
  "Wo der Eid brach": "Where the Oath Broke",
  "Wo der Name verweht": "Where the Name Blows Away",
  "Wo der Riss ausblutet": "Where the Rift Bleeds Out",
  "Wo der letzte Riegel fiel": "Where the Last Bolt Fell",
  "Wo die Erde trank": "Where the Earth Drank",
  "Wo die Lanze fällt": "Where the Lance Falls",
  "Wo die Lanze fällt II": "Where the Lance Falls II",
  "Wo die Sense ruht": "Where the Scythe Rests",
  "Wo die Treppe hinabführt": "Where the Stair Leads Down",
  "Wogenmark": "Billow March",
  "Wolfsfalle": "Wolf Trap",
  "Wolfsgrube": "Wolf Pit",
  "Wolfspass": "Wolf Pass",
  "Wolkenstube": "Cloud Parlour",
  "Wrack der Morgenröte": "Wreck of the Dawn",
  "Wrackaltar": "Wreck Altar",
  "Wracklichter": "Wreck Lights",
  "Wundaltar": "Wound Altar",
  "Wundklause": "Wound Hermitage",
  "Wurzelgewölbe": "Root Vault",
  "Wurzelstieg": "Root Track",
  "Wächtenkamm": "Cornice Crest",
  "Wächtenwall": "Cornice Rampart",
  "Zehntscheune": "Tithe Barn",
  "Zehntwacht": "Tithe Watch",
  "Zehrfeuer": "Wasting Fire",
  "Zeltasche": "Tent Ash",
  "Zerborstene Stufen": "The Shattered Steps",
  "Zerrissene Standarte": "The Torn Standard",
  "Zinnendorn": "Merlon Thorn",
  "Zinnoberaltar": "Vermilion Altar",
  "Zunderflur": "Tinder Flat",
  "Zunderflur II": "Tinder Flat II",
  "Zundermoos": "Tinder Moss",
  "Zunderspalte": "Tinder Cleft",
  "Zwergkiefer": "Dwarf Pine",
  "Zwieselgrund": "Forked Ground",
  "Zwillingsfeste": "Twin Hold",
  "Zwölf Türen": "Twelve Doors",
  "Ödgrat": "Barren Ridge",
  "Über die Baumgrenze": "Above the Treeline",
};

/** Der Name einer Station in der gewaehlten Sprache. Ohne Treffer bleibt der
 *  deutsche Name stehen - eine Station ohne Namen waere schlimmer als eine
 *  mit dem falschen. */
export const placeEn = (de) => (de && PLACE_EN[de]) || de || "";
