// ── Place names, per league, tied to the Chronicle of the Rift ───────────────
// League I keeps the authored homeland names from campaign.js. Leagues II–X
// each get their OWN full set of 51 hand-written names, drawn from that biome's
// chapter of the saga (the Judge's supervised wheat, the amber oaths that
// turned, the Keeper's bolted doors, Osric's bleeding sea …).
//
// DESIGN RULE (what this rewrite fixes): no mechanical prefix/suffix series.
// The old table gave the SAME station the same root word in every league with
// only a biome prefix swapped in ("Saatwacht / Frostwacht / Sandwacht",
// "Kornmühle / Sandmühle / Tidemühle"). Here every station is its own place —
// a name that could stand on a real map — and none repeats anywhere across the
// whole journey (a test in test_maps.mjs asserts zero duplicates, incl. L1).
//
// Keyed by node id. The id order below is fixed so each league's 51 names line
// up one-to-one with the same stations.

const IDS = [
  "n01","n02","n03","a1","a2","a3","a4","a5","b1","b2","b3","b4","b5",
  "c1","c2","c3","c4","c5","n16","n17","d1","d2","e1","e2","e3","n20","n21","n22",
  "g4","g5","g6","g7","g8","g9","g1","g2","g3","z1","z2","w1","w3","w2",
  "s1","s2","u1","u2","u3","o1","o2","o3","r1",
];

const zip = (names) => {
  const out = {};
  IDS.forEach((id, i) => { out[id] = names[i]; });
  return out;
};

export const PLACE_NAMES = {
  // ── II · Sommer — the golden fields; the Judge holds court in the wheat ──────
  2: zip([
    "Sichelmark",
    "Zehntwacht",
    "Kapelle im Korn",
    "Garbenwall",
    "Krähenschreck",
    "Der lange Acker",
    "Wo die Sense ruht",
    "Spreugericht",
    "Mittsommerbank",
    "Lerchenhorst",
    "Dreschhof",
    "Schwelrain",
    "Brandblatt",
    "Volle Scheuer",
    "Lindensitz",
    "Fürstenmahd",
    "Der Steinerne Pflug",
    "Grenzmark",
    "Kanzel im Weizen",
    "Waage und Wort",
    "Glutstoppel",
    "Fronburg",
    "Leere Scheune",
    "Wetterhahnturm",
    "Wende des Lichts",
    "Königsstroh",
    "Aschengarbe",
    "Osrics Speicher",
    "Fuhrmannsrast",
    "Dürretor",
    "Erntewiege",
    "Mohnwerder",
    "Gebeugte Kapelle",
    "Sichelbucht",
    "Flammenfurt",
    "Halmbruch",
    "Dörrkammer",
    "Windfähre",
    "Mautbalken",
    "Bei den Schnittern",
    "Der Schweigende Halm",
    "Welkgart",
    "Grannengasse",
    "Käferzinne",
    "Storchensitz",
    "Verlorene Garbe",
    "Ährengold",
    "Röstofen",
    "Brachjahr",
    "Kaffwind",
    "Mäusekirche",
  ]),

  // ── III · Herbst — the amber woods where the first oaths turned ─────────────
  3: zip([
    "Erstes Rot",
    "Rostlaube",
    "Bernsteinaltar",
    "Kastanienhall",
    "Ockergrund",
    "Der Rehpfad",
    "Wo der Eid brach",
    "Klingenwald",
    "Erntedank",
    "Drosselsang",
    "Schwelnest",
    "Falbes Licht",
    "Fallendes Laub",
    "Zwillingsfeste",
    "Lindenschatten",
    "Amselthron",
    "Der Rostige Riegel",
    "Laubpresse",
    "Wipfelkanzel",
    "Halle der zwei Schwüre",
    "Harzträne",
    "Pilzring",
    "Morschenburg",
    "Sturmlaub",
    "Dämmerlaube",
    "Königslaub",
    "Gilbfeuer",
    "Der geteilte Schwur",
    "Köhlersitz",
    "Moderpforte",
    "Wandererrast",
    "Eichelschatz",
    "Verhüllter Altar",
    "Treibholzufer",
    "Fuchsfurt",
    "Wurzelgewölbe",
    "Eulenwarte",
    "Blätterkahn",
    "Ahornbrück",
    "Marderschlupf",
    "Der Stumme Hain",
    "Modergraben",
    "Reisigschneise",
    "Ameisenhügel",
    "Dornenkessel",
    "Maronengrube",
    "Otternwinkel",
    "Harzader",
    "Falllaubdecke",
    "Stoppelhang",
    "Rost und Reue",
  ]),

  // ── IV · Winter — the cold preserves what the rift changes; the Shadowlord ──
  4: zip([
    "Erster Frost",
    "Klammglocke",
    "Vereister Altar",
    "Jägersitz",
    "Firnriss",
    "Die Wolfsspur",
    "Wo der Atem gefror",
    "Eisnadel",
    "Kerzenmesse",
    "Polarnacht",
    "Raureifgitter",
    "Blaue Stunde",
    "Wächtenwall",
    "Eisburg",
    "Schneelinde",
    "Frostthron",
    "Der Zugefrorene Riegel",
    "Fährtenfeld",
    "Nordlichtkanzel",
    "Halle der stillen Kälte",
    "Taustelle",
    "Gipfelruh",
    "Verwaiste Hütte",
    "Lawinenhang",
    "Barfußspur",
    "Königsfrost",
    "Grabesschnee",
    "Der Fürst im Halbschatten",
    "Jägersteig",
    "Das Erfrorene Tor",
    "Rast der Erschöpften",
    "Schneegrenze",
    "Vereiste Klause",
    "Eisbucht",
    "Splitterbrück",
    "Frostbeulen",
    "Gefrorene Träne",
    "Eiskahn",
    "Knirschsteg",
    "Fallenstellerlager",
    "Der Erstarrte Hain",
    "Reifrosen",
    "Firnscharte",
    "Frostglockenturm",
    "Wächtenkamm",
    "Wolfsgrube",
    "Rabenwinter",
    "Quellen unterm Eis",
    "Weißer Schlaf",
    "Schneeblinde",
    "Letzte Flocke",
  ]),

  // ── V · Hochgebirge — over these passes fled the court; the Keeper's keys ────
  5: zip([
    "Erster Grat",
    "Meißelschlag",
    "Gipfelaltar",
    "Steinmetzsitz",
    "Geröllzunge",
    "Der Gamssteig",
    "Wo der letzte Riegel fiel",
    "Kluftfeste",
    "Adlermesse",
    "Wolkenstube",
    "Splitterkar",
    "Dohlenflug",
    "Firnhang",
    "Hochwacht",
    "Zwergkiefer",
    "Gipfelkron",
    "Das Verlorene Schloss",
    "Schutthalde",
    "Adlerkanzel",
    "Halle der leeren Regale",
    "Schlüsselbund",
    "Sieben Riegel",
    "Verfallene Klause",
    "Donnerkar",
    "Sternenlager",
    "Königsjoch",
    "Grauer Atem",
    "Der Hüter ohne Tür",
    "Seilpfad",
    "Das Verriegelte Tor",
    "Rast am Abgrund",
    "Grathelm",
    "Steinerne Stube",
    "Gletschermilch",
    "Hängender Weiler",
    "Murmelloch",
    "Kristallader",
    "Seilwinde",
    "Schwindelsteg",
    "Bei den Steinmetzen",
    "Der Kahle Rücken",
    "Flechtenteppich",
    "Klufttreppe",
    "Schlüsselzinne",
    "Nebelmeerblick",
    "Schieferwiege",
    "Steinbockstand",
    "Tropfstein",
    "Ödgrat",
    "Echostille",
    "Zwölf Türen",
  ]),

  // ── VI · Ödland — the first price the rift drank; the Bloodmaid's chalice ────
  6: zip([
    "Erster Riss",
    "Staubglocke",
    "Wundaltar",
    "Plünderersitz",
    "Splitterknochen",
    "Der Galgenpfad",
    "Wo die Erde trank",
    "Dornenkelch",
    "Kelchmesse",
    "Fahles Land",
    "Sprödes Bett",
    "Grauschleier",
    "Totes Geäst",
    "Dornenfeste",
    "Graudorn",
    "Dornendiadem",
    "Das Ausgeblutete Tor",
    "Rabenacker",
    "Kanzel der Wunde",
    "Halle des vollen Kelchs",
    "Bittersalz",
    "Galgenhöhe",
    "Verlassene Kate",
    "Staubwalze",
    "Letzter Schluck",
    "Königsdurst",
    "Zehrfeuer",
    "Die Magd am Kelch",
    "Marterpfad",
    "Das Rostige Tor",
    "Rast der Verlorenen",
    "Aschepfand",
    "Wundklause",
    "Lakensenke",
    "Blutzoll",
    "Hohlzahn",
    "Geierwarte",
    "Knochenfloß",
    "Wackelsteg",
    "Krähenbankett",
    "Der Verdorrte Hain",
    "Distelacker",
    "Rinnsal",
    "Der Schiefe Galgen",
    "Dürrejahr",
    "Grubenlicht",
    "Geiergericht",
    "Tropfenzähler",
    "Ödnisrand",
    "Schlackenzunge",
    "Stimmen im Staub",
  ]),

  // ── VII · Steppe — tourneys were ridden here; the Lancemaster rides them yet ─
  7: zip([
    "Weites Rund",
    "Hufdonner",
    "Reiteraltar",
    "Jurtenring",
    "Zunderflur",
    "Der Wildwechsel",
    "Wo die Lanze fällt",
    "Grasmeer",
    "Turniermesse",
    "Freier Himmel",
    "Stutenmilch",
    "Flirrende Luft",
    "Fahnenwind",
    "Sattelfeste",
    "Steppenulme",
    "Steppenkron",
    "Der Ferne Riegel",
    "Bannergrund",
    "Falkenkanzel",
    "Halle des einen Gangs",
    "Mirenns Brunnen",
    "Hoher Ausguck",
    "Verlassene Jurte",
    "Böenritt",
    "Letzte Schranke",
    "Königsweide",
    "Zerrissene Standarte",
    "Der Meister der Lanze",
    "Viehtrift",
    "Das Ferne Tor",
    "Rast der Reiter",
    "Hufschlagring",
    "Grasklause",
    "Schilfmeer",
    "Stromschnellenfurt",
    "Hufeisenglück",
    "Murmeltierstadt",
    "Grasklinge",
    "Bohlenweg",
    "Bei den Pferdehirten",
    "Der Wispernde Halm",
    "Zeltasche",
    "Weidewende",
    "Späherzinne",
    "Trockene Tränke",
    "Wolfsfalle",
    "Geierschatten",
    "Siegerquell",
    "Brandschneise",
    "Distelwind",
    "Lied der Weite",
  ]),

  // ── VIII · Roter Canyon — the wound itself; the last stair down; Ironfist ────
  8: zip([
    "Oberkante",
    "Hammerschlag",
    "Zinnoberaltar",
    "Räubersitz",
    "Geröllrutsche",
    "Der Kondorpfad",
    "Wo die Treppe hinabführt",
    "Messerschlucht",
    "Steinmesse",
    "Kupferader",
    "Abbruchkante",
    "Flimmerhitze",
    "Glutofen",
    "Felsenhorst",
    "Zinnendorn",
    "Glutkamm",
    "Das Berstende Tor",
    "Schwalbennische",
    "Kondorkanzel",
    "Halle der geballten Faust",
    "Blasebalg",
    "Aussichtsnadel",
    "Verlassener Stollen",
    "Steinschlag",
    "Tiefenblick",
    "Königsschlucht",
    "Rostregen",
    "Die Faust am Grund",
    "Maultiersteige",
    "Das Glühende Tor",
    "Rast am Schlund",
    "Zerborstene Stufen",
    "Einsiedlerloch",
    "Windgeschliffen",
    "Furtlose Enge",
    "Scherbengrat",
    "Tropfsteinorgel",
    "Seilrolle",
    "Hängebrück",
    "Grubenlampen",
    "Der Versteinerte Hain",
    "Dornengesims",
    "Talenge",
    "Wachtfels",
    "Ockerwanne",
    "Schuttrinne",
    "Bussardstand",
    "Heiße Quelle",
    "Eisenblüte",
    "Zunderspalte",
    "Atem der Wunde",
  ]),

  // ── IX · Wüste — swallows names; only the oasis remembers; the Cannoneer ─────
  9: zip([
    "Trockentor",
    "Karawanenglocke",
    "Dünenaltar",
    "Lastenrast",
    "Dornengürtel",
    "Der Fennekpfad",
    "Wo der Name verweht",
    "Spiegelung",
    "Oasenmesse",
    "Sieben Palmen",
    "Glasfeld",
    "Fata Morgana",
    "Wanderdüne",
    "Karawanserei",
    "Dattelhain",
    "Sonnenspeer",
    "Das Versandete Tor",
    "Salzkruste",
    "Geierkanzel",
    "Halle des letzten Tors",
    "Vesnas Schatten",
    "Hoher Kamm",
    "Vergessene Zisterne",
    "Sandhose",
    "Gebleichte Rippen",
    "Königsdüne",
    "Glutspiegel",
    "Der Kanonier am Wasser",
    "Kamelspur",
    "Das Flüsternde Tor",
    "Rast der Durstigen",
    "Dünenwerder",
    "Sandklause",
    "Palmschatten",
    "Wasserprobe",
    "Skarabäenfeld",
    "Blaue Grotte",
    "Treibsandfalle",
    "Seilbrück",
    "Bei den Wasserträgern",
    "Der Singende Fels",
    "Bleichgart",
    "Sichelgrab",
    "Spiegelzinne",
    "Ausgetrocknet",
    "Schlangenloch",
    "Stachelnest",
    "Tiefbrunnen",
    "Namenlose Weite",
    "Sternenpfad",
    "Stille vor Mittag",
  ]),

  // ── X · Endloses Meer — where the rift bleeds out; Osric waits; the Captain ──
  10: zip([
    "Erste Gischt",
    "Tidenglocke",
    "Wrackaltar",
    "Strandgutlese",
    "Muschelscherben",
    "Der Möwenstrich",
    "Wo der Riss ausblutet",
    "Gezeitenklinge",
    "Leuchtfeuermesse",
    "Kap der Fracht",
    "Kalter Sog",
    "Milchsee",
    "Wogenmark",
    "Wellenwacht",
    "Tangwald",
    "Gischtthron",
    "Das Berstende Gatter",
    "Treibnetz",
    "Möwenkanzel",
    "Halle der herrenlosen Fracht",
    "Kielwasser",
    "Krähennest",
    "Verlassener Kai",
    "Sturmglas",
    "Bleicher Horizont",
    "Königsklippe",
    "Aschesegel",
    "Osrics letztes Tor",
    "Wracklichter",
    "Das Ertrunkene Tor",
    "Rast der Gestrandeten",
    "Piersplitter",
    "Brackwasserklause",
    "Ankerfriedhof",
    "Salzlippen",
    "Flaschenpost",
    "Perlmuttgrotte",
    "Fährmannsruf",
    "Planke über Schwarz",
    "Bei den Strandläufern",
    "Die Stille See",
    "Seegraswiege",
    "Ebbe und Niemand",
    "Der Leuchtturm",
    "Robbenbank",
    "Tintengrund",
    "Krakenwache",
    "Süßwasserlinse",
    "Horizontlos",
    "Letzte Boje",
    "Lied unter Wasser",
  ]),
};
