// ── Place names, per league, tied to the Chronicle of the Rift ───────────────
// League I keeps the authored homeland names from campaign.js. Leagues II–X
// each get their OWN full set of 51 hand-written names, drawn from that biome's
// chapter of the saga (the Judge's supervised wheat, the amber oaths that
// turned, the Keeper's bolted doors, Osric's bleeding sea …).
//
// DESIGN RULE (what this rewrite fixes): no mechanical prefix/suffix series.
// The old table gave the SAME station the same root word in every league with
// only a biome prefix swapped in ("Saatwacht / Frostwacht / Sandwacht",
// "Kornmühle / Sandmühle / Tidemühle"). Here every station is its own place —
// a name that could stand on a real map — and none repeats anywhere across the
// whole journey (a test in test_maps.mjs asserts zero duplicates, incl. L1).
//
// Keyed by node id. The id order below is fixed so each league's 51 names line
// up one-to-one with the same stations.

const IDS = [
  "n01","n02","n03","a1","a2","a3","a4","a5","b1","b2","b3","b4","b5",
  "c1","c2","c3","c4","c5","n16","n17","d1","d2","e1","e2","e3","n20","n21","n22",
  "g4","g5","g6","g7","g8","g9","g1","g2","g3","z1","z2","w1","w3","w2",
  "s1","s2","u1","u2","u3","o1","o2","o3","r1",
];

const zip = (names) => {
  const out = {};
  IDS.forEach((id, i) => { out[id] = names[i]; });
  return out;
};

export const PLACE_NAMES = {
  // ── II · Sommer — the golden fields; the Judge holds court in the wheat ──────
  2: zip([
    "Erstschnitt", "Goldkammer", "Kapelle im Korn", "Halmgrund", "Bei den Vogelscheuchen", "Der lange Acker",
    "Wo die Sense ruht", "Spelzengrund", "Sonntag", "Mittsommerblick", "Distelbruch", "Am schwelenden Rain",
    "Verbranntes Feld", "Speicher der Zehnten", "Lindgrund", "Fürstenmahd", "Der Steinerne Pflug", "Grenzrain",
    "Kanzel im Weizen", "Waage und Wort", "Glutgrund", "Auf der Fronhöhe", "Leere Scheune", "Wetterhorst",
    "Wende des Lichts", "Königsstroh", "Aschrain", "Osrics Speicher",
    "Am Fuhrweg", "Das Verdorrte Tor", "Wiege der Ernte", "Der Verscharrte Weg", "Gebeugte Kapelle", "Sichelbucht",
    "Furt der Flammen", "Bruch im Halm", "Dörrgrund", "Fähre im Wind", "Zehntsteg", "Bei den Schnittern",
    "Der Schweigende Halm", "Welkgarten", "Grannental", "Der Käferturm", "Dörrmulde", "Verlorene Garbe",
    "Distelhorst", "Röste", "Brachgrund", "Kaffgrund", "Spreuhall",
  ]),

  // ── III · Herbst — the amber woods where the first oaths turned ─────────────
  3: zip([
    "Erstes Rot", "Rostwerk", "Bernsteinaltar", "Kastanienhang", "Ockerbruch", "Der Rehpfad",
    "Wo der Eid brach", "Klingental", "Erntedank", "Drosselblick", "Schwelbruch", "Nebelrain",
    "Fallendes Laub", "Zwillingsburg", "Lindenschatten", "Herbstkrone", "Der Rostige Riegel", "Laubwall",
    "Wipfelkanzel", "Halle der zwei Schwüre", "Harzgrund", "Auf der Wipfelhöhe", "Morsche Scheune", "Sturmlaub",
    "Zwielichtblick", "Königslaub", "Aschlaub", "Der geteilte Schwur",
    "Am Köhlerweg", "Das Morsche Tor", "Rast der Wandernden", "Der Verwehte Weg", "Verhüllter Altar", "Treibholzbucht",
    "Flammfurt", "Bruch im Laub", "Harzgrotte", "Blätterfähre", "Ahornsteg", "Bei den Köhlern",
    "Der Stumme Hain", "Modergarten", "Reisigtal", "Der Ameisenturm", "Dornenmulde", "Modergrube",
    "Otternhorst", "Harzquell", "Falllaubgrund", "Stoppelhang", "Echo im Rost",
  ]),

  // ── IV · Winter — the cold preserves what the rift changes; the Shadowlord ──
  4: zip([
    "Erster Frost", "Klammwerk", "Vereister Altar", "Jägerhang", "Firnbruch", "Der Wolfsspur-Pfad",
    "Wo der Atem gefror", "Eisklinge", "Kerzenmesse", "Polarblick", "Klammbruch", "Nebelfirn",
    "Schneewehen", "Eisburg", "Schneelinde", "Winterkrone", "Der Zugefrorene Riegel", "Firnwall",
    "Nordlichtkanzel", "Halle der stillen Kälte", "Taugrund", "Auf der Gipfelhöhe", "Verwaiste Scheune", "Firnsturm",
    "Nordlichtblick", "Königsfrost", "Aschschnee", "Der Fürst im Halbschatten",
    "Am Jägerweg", "Das Erfrorene Tor", "Rast der Erschöpften", "Der Verschüttete Weg", "Vereiste Klause", "Eisbucht",
    "Frostfurt", "Bruch im Eis", "Eisgrotte", "Eisfähre", "Firnsteg", "Bei den Jägern",
    "Der Erstarrte Hain", "Reifgarten", "Firntal", "Der Frostturm", "Klammmulde", "Frostgrube",
    "Eishorst", "Tauquell", "Firngrund", "Schneegrund", "Echo im Eis",
  ]),

  // ── V · Hochgebirge — over these passes fled the court; the Keeper's keys ────
  5: zip([
    "Erster Grat", "Steinbruchwerk", "Gipfelaltar", "Steinmetzhang", "Gratbruch", "Der Gamspfad",
    "Wo der letzte Riegel fiel", "Steinklinge", "Adlermesse", "Gipfelblick", "Felsbruch", "Nebelgrat",
    "Firnhang", "Steinburg", "Zwergkiefer", "Gipfelkrone", "Das Verlorene Schloss", "Gratwall",
    "Adlerkanzel", "Halle der leeren Regale", "Bergquell", "Auf der Firnhöhe", "Verfallene Klause", "Firngrat-Sturm",
    "Sternenblick", "Königssteig-Höh", "Aschgrat", "Der Hüter ohne Tür",
    "Am Seilweg", "Das Verriegelte Tor", "Rast am Abgrund", "Der Gesprengte Grat", "Steinerne Klause", "Gletscherbucht",
    "Steinfurt", "Bruch im Fels", "Felsgrotte", "Seilfähre", "Steinsteg", "Bei den Steinmetzen",
    "Der Kahle Hain", "Steingarten", "Klammtal", "Der Steinturm", "Felsmulde", "Felsgrube",
    "Steinhorst", "Bergquell-Ost", "Firngrat", "Gratgrund", "Echo im Stein",
  ]),

  // ── VI · Ödland — the first price the rift drank; the Bloodmaid's chalice ────
  6: zip([
    "Erster Riss", "Staubwerk", "Wundaltar", "Plünderhang", "Rissbruch", "Der Galgenpfad",
    "Wo die Erde trank", "Dornklinge", "Kelchmesse", "Verfallblick", "Ödbruch", "Nebeldunst",
    "Totes Geäst", "Dornenburg", "Graudorn", "Aschekrone", "Das Ausgeblutete Tor", "Ödwall",
    "Kanzel der Wunde", "Halle des vollen Kelchs", "Ödquell", "Auf der Galgenhöhe", "Verlassene Kate", "Staubsturm",
    "Fahler Blick", "Königsstaub", "Aschgrund", "Die Magd am Kelch",
    "Am Plünderweg", "Das Rostige Tor", "Rast der Verlorenen", "Der Verschüttete Ödweg", "Wundklause", "Salzbucht",
    "Blutfurt", "Bruch im Staub", "Aschgrotte", "Aschfähre", "Knochensteg", "Bei den Plünderern",
    "Der Verdorrte Hain", "Aschgarten", "Ödtal", "Der Aschturm", "Trockenmulde", "Staubgrube",
    "Ödhorst", "Sickerquell", "Brachöd", "Schlackengrund", "Echo im Staub",
  ]),

  // ── VII · Steppe — tourneys were ridden here; the Lancemaster rides them yet ─
  7: zip([
    "Weites Rund",
    "Windwerk",
    "Reiteraltar",
    "Nomadenhang",
    "Trampelpfad",
    "Wo die Lanze fällt",
    "Wildpfad",
    "Schilflunge",
    "Turniermesse",
    "Freier Blick",
    "Riedbruch",
    "Nebelküste",
    "Gewindeturm",
    "Falkenhorst",
    "Steppenkrone",
    "Ferner Riegel",
    "Grasburg",
    "Heideklaue",
    "Falkenkanzel",
    "Halle des einen Gangs",
    "Brunnen Mirenn",
    "Auf der Weidehöhe",
    "Verlassene Jurte",
    "Böensturm",
    "Königsweide",
    "Letzter Stall",
    "Zundergras",
    "Der Meister der Lanze",
    "Nomadenweg",
    "Fernes Tor",
    "Rast der Reiter",
    "Schilfbucht",
    "Pferdegrab",
    "Bruch im Wind",
    "Riedgrotte",
    "Strohfähre",
    "Ruchsteg",
    "Bei den Nomaden",
    "Otterhorst",
    "Riedgarten",
    "Weidetal",
    "Nomadenturm",
    "Sattelmulde",
    "Heidegrube",
    "Steppenquell",
    "Heuschober",
    "Brachsteppe",
    "Riedgrund",
    "Echo im Wind",
    "Wüstengürtel",
    "Staubscheide",
  ]),

  // ── VIII · Roter Canyon — the wound itself; the last stair down; Ironfist ────
  8: zip([
    "Erster Abstieg", "Klammwerk am Fels", "Rotaltar", "Räuberhang", "Rotbruch", "Der Kondorpfad",
    "Wo die Treppe hinabführt", "Rotklinge", "Steinmesse", "Kupferblick", "Klammbruch am Grat", "Nebelrot",
    "Rotfeld", "Rotburg", "Rotdorn", "Kupferkrone", "Das Berstende Tor", "Rotwall",
    "Kondorkanzel", "Halle der geballten Faust", "Glutquell", "Auf der Kupferhöhe", "Verlassener Stollen", "Rotsturm",
    "Klammblick", "Königsschlucht", "Aschrot", "Die Faust am Grund",
    "Am Räuberweg", "Das Rotberstende Tor", "Rast am Schlund", "Der Zerborstene Weg", "Rotklause", "Felsbucht",
    "Rotfurt", "Bruch im Rot", "Rotgrotte", "Felsfähre", "Rotsteg", "Bei den Räubern",
    "Der Verbrannte Hain", "Rotgarten", "Rottal", "Der Felsturm", "Rotmulde", "Rotgrube",
    "Felshorst", "Glutquell-Ost", "Brachrot", "Schlackenrot", "Echo im Rot",
  ]),

  // ── IX · Wüste — swallows names; only the oasis remembers; the Cannoneer ─────
  9: zip([
    "Trockentor",
    "Karawanenwerk",
    "Dünenaltar",
    "Karawanenhang",
    "Dornbruch",
    "Fennekpfad",
    "Wo der Name verweht",
    "Dattelklinge",
    "Oasenmesse",
    "Dünenblick",
    "Trockene Rinne",
    "Nebeldüne",
    "Wüstenfeld",
    "Karawanserei-Ruine",
    "Dattelhain",
    "Sandkrone",
    "Versandetes Tor",
    "Karawanenmauer",
    "Geierkanzel",
    "Halle des letzten Tors",
    "Sickerquelle",
    "Auf der Dünenhöhe",
    "Stille Karawanserei",
    "Körnersturm",
    "Ausgebleichter Hang",
    "Königsdüne",
    "Aschedüne",
    "Der Kanonier am Wasser",
    "Karawanenweg",
    "Flüsterndes Tor",
    "Rast der Durstigen",
    "Palmenbucht",
    "Verwehter Weg",
    "Knochen im Schritt",
    "Brunnen im Nichts",
    "Grottenquelle",
    "Staubfähre",
    "Haltsteg",
    "Durstbrücke",
    "Bei den Karawanen",
    "Singender Hain",
    "Ausgebleichter Garten",
    "Dornentalschlucht",
    "Wächterturm",
    "Brennende Mulde",
    "Verdorrte Grube",
    "Skorpionhorst",
    "Oasenquell",
    "Brachöde",
    "Schlackenstaub",
    "Echo der Stille",
  ]),

  // ── X · Endloses Meer — where the rift bleeds out; Osric waits; the Captain ──
  10: zip([
    "Erste Gischt",
    "Tidenwerk",
    "Wrackaltar",
    "Strandguthang",
    "Riffbruch",
    "Möwenpfad",
    "Wo der Riss ausblutet",
    "Gezeitenklinge",
    "Leuchtfeuermesse",
    "Klippenblick",
    "Kalter Grund",
    "Nebelsee",
    "Wogenfeld",
    "Wellenburg",
    "Tangwald",
    "Klippenkrone",
    "Berstendes Tor",
    "Tidenwall",
    "Möwenkanzel",
    "Halle der herrenlosen Fracht",
    "Mündungsbucht",
    "Auf der Klippenhöhe",
    "Verlassener Kai",
    "Wogensturm",
    "Fahler Klippenblick",
    "Königsklippe",
    "Aschsee",
    "Osrics letztes Tor",
    "Am Strandgutweg",
    "Flüsterndes Hafentor",
    "Rast der Gestrandeten",
    "Zerborstener Kai",
    "Brackwasserklause",
    "Ankergrund",
    "Gezeitenfurt",
    "Bruch im Riff",
    "Meeresgrotte",
    "Wellenfähre",
    "Wracksteg",
    "Bei den Strandläufern",
    "Stille See",
    "Tanggarten",
    "Rifftal",
    "Leuchtturm",
    "Riffmulde",
    "Seegrube",
    "Krakenhorst",
    "Tidenquell",
    "Brachsee",
    "Schlacksee",
    "Echo im Riff",
  ]),
};
