// Reads every SVG in assets/pieces + assets/scenery and writes
// src/app/ui/art.generated.js — the registry the game renders from.
// Edit an SVG (Inkscape, Illustrator, Texteditor), run `npm run art`
// (or just build/test — it runs automatically), done.
// The link is the root attribute data-gg="piece:P" / "scenery:pine" /
// "boss:beast" / "crest" — file NAMES are free to change.
import { readFileSync, writeFileSync, readdirSync } from "fs";

const inner = (svg) => {
  let s = svg.replace(/<\?xml[\s\S]*?\?>/g, "").replace(/<!--[\s\S]*?-->/g, "");
  s = s.replace(/<metadata[\s\S]*?<\/metadata>/g, "").replace(/<sodipodi:[\s\S]*?\/>/g, "");
  const m = s.match(/<svg\b[^>]*>([\s\S]*)<\/svg>/);
  return m ? m[1].trim() : "";
};
const gg = (svg) => (svg.match(/data-gg="([^"]+)"/) || [])[1];

const piece = {}, boss = {}, scenery = {}; let crest = "";
for (const [dir, kinds] of [["assets/pieces", true], ["assets/scenery", false]]) {
  for (const f of readdirSync(dir)) {
    if (!f.endsWith(".svg")) continue;
    const svg = readFileSync(`${dir}/${f}`, "utf8");
    const tag = gg(svg);
    if (!tag) { console.warn(`  ! ${dir}/${f}: kein data-gg-Attribut — übersprungen`); continue; }
    const body = inner(svg);
    const [type, key] = tag.split(":");
    if (type === "piece") piece[key] = body;
    else if (type === "boss") boss[key] = body;
    else if (type === "crest") crest = body;
    else if (type === "scenery") scenery[key] = body;
  }
}
const J = (o) => JSON.stringify(o, null, 0);
writeFileSync("src/app/ui/art.generated.js",
`// AUTO-GENERATED by scripts/build-art.mjs — DO NOT EDIT.
// Source of truth: assets/pieces/*.svg and assets/scenery/*.svg
// (edit those, then \`npm run art\`).
export const PIECE_ART = ${J(piece)};
export const BOSS_ART = ${J(boss)};
export const CREST_ART = ${JSON.stringify(crest)};
export const SCENERY_ART = ${J(scenery)};
`);
console.log(`art: ${Object.keys(piece).length} pieces, ${Object.keys(boss).length} bosses, crest, ${Object.keys(scenery).length} scenery`);
